env:
  theme: "flatly"
  template: "template/index.jade"
  destination-folder: "generated_doc"

pages:
  index:
    input: index.md
    output: index.html
  how-to-write-API-doc:
    input: how-to-write-API-doc.md
    output: technical/how-to-write-API-doc.html
#  api_club:
#    path: how-to-write-API-doc.md
#    folder: technical

menu:
#  api:
#      title: Api Documentation
#  apis:
#      title: APIs
#      children:
#          page1:
#            title: API clubs
#            page_key:
  doc-functional:
      title: Docs Techniques
      children:
        page1:
          title: "Comment écrire dans l'API"
          page-key: how-to-write-API-doc
  doc-functional2:
      title: Docs Techniques
      children:
        page1:
          title: "Comment écrire dans l'API"
          page-key: how-to-write-API-doc